# Prettier Configuration
# See: https://prettier.io/docs/en/configuration.html

printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: 'as-needed'
jsxSingleQuote: true
trailingComma: 'es5'
bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'
endOfLine: 'lf'
embeddedLanguageFormatting: 'auto'

# Astro specific
overrides:
  - files: '*.astro'
    options:
      parser: 'astro'
  - files: '*.md'
    options:
      tabWidth: 2
      printWidth: 80
  - files: '*.json'
    options:
      tabWidth: 2